name: Linting

on: [ push ]

jobs:
  editorconfig-checker:
    name: Run Editorconfig-Checker
    runs-on: ubuntu-latest
    container: mstruebing/editorconfig-checker:latest
    steps:
      - uses: actions/checkout@v2
      - run: ec
      - name: Send Telegram notification about failure
        uses: appleboy/telegram-action@master
        if: ${{ failure() }}
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Your WAI2 project contains EditorConfig violations!
