name: Linting

on: [ push, pull_request ]

jobs:
  editorconfig-checker:
    name: Run Editorconfig-Checker
    runs-on: ubuntu-latest
    container: mstruebing/editorconfig-checker:latest
    steps:
      - uses: actions/checkout@v2
      - run: ec
